version: '3.8'

services:

  ubuntu:
    container_name: ubuntu-redes
    image: ubuntu-redes-img
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    ports:
      - 8080:8080
    volumes:
      - .:/home/workspace